schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: ${DATOCMS_FULL_ACCESS_API_TOKEN}
documents: './graphql/**/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations:
          strictScalars: true
          scalars:
            BooleanType: boolean
            CustomData: Record<string, unknown>
            Date: string
            DateTime: string
            FloatType: number
            IntType: number
            ItemId: string
            JsonField: unkown
            MetaTagAttributes: Record<string, string>
            UploadId: string
      - typed-document-node
