schema:
  - ${NEXT_PUBLIC_HYGRAPH_API_ENDPOINT}:
      headers:
        Authorization: ${NEXT_PUBLIC_HYGRAPH_API_TOKEN}
documents: './graphql/**/*.graphql'
generates:
  graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
